/**
 * Dati dei quattro DVR Microclima modello (Castagnola 2025 galleria inverno ed estate, CTG 2025 esterno estivo,
 * Xenia 2026 opere in esterno inverno). Estratti dai documenti: non modificare a mano.
 */
import type {
  LavorazioneMicroclima,
  MansioneMicroclima,
  MeseMeteo,
  RilievoMicroclima,
} from "../valutazione";

interface Scenario {
  mansioni: MansioneMicroclima[];
  rilievi: RilievoMicroclima[];
  lavorazioni: LavorazioneMicroclima[];
}

export const GALLERIA_INVERNO: Scenario = {
  mansioni: [
    { id: "galleriaInverno-m1", nome: "Perforatore" },
    { id: "galleriaInverno-m2", nome: "Jumbista/Minatore" },
    {
      id: "galleriaInverno-m3",
      nome: "Jumbista/Minatore/Palista/Mulettista/Camionista",
    },
    { id: "galleriaInverno-m4", nome: "Fochino/Minatore/Gruista" },
    { id: "galleriaInverno-m5", nome: "Fochino/Minatore/Mulettista/Autista" },
    { id: "galleriaInverno-m6", nome: "Responsabile Consolidamenti" },
    { id: "galleriaInverno-m7", nome: "Caposquadra Minatore" },
    { id: "galleriaInverno-m8", nome: "Escavatorista/Palista" },
    { id: "galleriaInverno-m9", nome: "Minatore" },
    { id: "galleriaInverno-m10", nome: "Minatore/Caposquadra/Lancista" },
    { id: "galleriaInverno-m11", nome: "Aiuto Lancista/Minatore" },
    { id: "galleriaInverno-m12", nome: "Disgaggiatore/Perforatore" },
    { id: "galleriaInverno-m13", nome: "Escavatorista/Palista/Mulettista" },
    { id: "galleriaInverno-m14", nome: "Caposquadra/Minatore" },
    { id: "galleriaInverno-m15", nome: "Lancista/Autista/Minatore" },
    { id: "galleriaInverno-m16", nome: "Lancista/Mulettista" },
    { id: "galleriaInverno-m17", nome: "Lancista/Autista/Mulettista" },
    {
      id: "galleriaInverno-m18",
      nome: "Minatore/Escavatorista/Palista/Autista",
    },
    { id: "galleriaInverno-m19", nome: "Lancista/Autista/Palista" },
    { id: "galleriaInverno-m20", nome: "Palista/Autista/Minatore" },
    { id: "galleriaInverno-m21", nome: "Autista/Minatore/Gruista" },
    { id: "galleriaInverno-m22", nome: "Autista/Minatore" },
    { id: "galleriaInverno-m23", nome: "Autista/Minatore/Mulettista" },
    { id: "galleriaInverno-m24", nome: "Escavatorista/Palista/Lancista" },
    {
      id: "galleriaInverno-m25",
      nome: "Escavatorista/Autista/Mulettista/Palista",
    },
    { id: "galleriaInverno-m26", nome: "Escavatorista/Palista/Caposquadra" },
    { id: "galleriaInverno-m27", nome: "Caposquadra/Carpentiere/Mulettista" },
    { id: "galleriaInverno-m28", nome: "Carpentiere/Mulettista" },
    { id: "galleriaInverno-m29", nome: "Carpentiere/Caposquadra" },
    { id: "galleriaInverno-m30", nome: "Carpentiere PLE" },
    { id: "galleriaInverno-m31", nome: "Carpentiere" },
    { id: "galleriaInverno-m32", nome: "Ferraiolo" },
    {
      id: "galleriaInverno-m33",
      nome: "Carpentiere/Ripristini/Mulettista/PLE",
    },
    { id: "galleriaInverno-m34", nome: "Carpenterie/Ripristini/Mulettista" },
    { id: "galleriaInverno-m35", nome: "Carpentiere/Ferraiolo" },
    { id: "galleriaInverno-m36", nome: "Addetto ripristini non conformità" },
    { id: "galleriaInverno-m37", nome: "Lancista/Autista" },
    { id: "galleriaInverno-m38", nome: "Aiuto Lancista" },
    { id: "galleriaInverno-m39", nome: "Capo officina/meccanico/saldatore" },
    { id: "galleriaInverno-m40", nome: "Capo elettricista/Elettricista" },
    { id: "galleriaInverno-m41", nome: "Capo elettricista/elettricista" },
  ],
  rilievi: [
    {
      id: "galleriaInverno-r1",
      codice: "MCR01",
      data: "20/12/2024",
      fase: "Perforazione del fronte per consolidamento",
      postazione: "In prossimità lavorazione",
      ta: 23.5,
      va: 0.33,
      ur: 65.6,
      tnw: 22.9,
      trugiada: 20.2,
      tg: 25.4,
    },
    {
      id: "galleriaInverno-r2",
      codice: "MCR02",
      data: "20/12/2024",
      fase: "Scavo/Disgaggio",
      postazione: "In prossimità lavorazione",
      ta: 24.0,
      va: 0.39,
      ur: 65.5,
      tnw: 22.9,
      trugiada: 20.3,
      tg: 25.5,
    },
    {
      id: "galleriaInverno-r3",
      codice: "MCR03",
      data: "20/12/2024",
      fase: "Smarino",
      postazione: "In prossimità lavorazione",
      ta: 24.3,
      va: 0.18,
      ur: 65.6,
      tnw: 23.1,
      trugiada: 20.3,
      tg: 25.5,
    },
    {
      id: "galleriaInverno-r4",
      codice: "MCR04",
      data: "20/12/2024",
      fase: "Posa centina",
      postazione: "In prossimità lavorazione",
      ta: 25.3,
      va: 0.31,
      ur: 65.1,
      tnw: 23.5,
      trugiada: 20.6,
      tg: 25.7,
    },
    {
      id: "galleriaInverno-r5",
      codice: "MCR05",
      data: "20/12/2024",
      fase: "Carpenteria in cassaforma",
      postazione: "In prossimità lavorazione",
      ta: 26.1,
      va: 0.2,
      ur: 65.6,
      tnw: 24.0,
      trugiada: 21.1,
      tg: 25.9,
    },
    {
      id: "galleriaInverno-r6",
      codice: "MCR06",
      data: "20/12/2024",
      fase: "Spritz",
      postazione: "In prossimità lavorazione",
      ta: 26.5,
      va: 0.24,
      ur: 65.9,
      tnw: 23.7,
      trugiada: 21.0,
      tg: 26.1,
    },
    {
      id: "galleriaInverno-r7",
      codice: "MCR07",
      data: "20/12/2024",
      fase: "Manutenzione mezzi - camerone",
      postazione: "Camerone",
      ta: 26.1,
      va: 0.88,
      ur: 65.6,
      tnw: 23.9,
      trugiada: 21.2,
      tg: 25.9,
    },
    {
      id: "galleriaInverno-r8",
      codice: "MCR08",
      data: "20/12/2024",
      fase: "Manutenzione straordinaria mezzi -dietro cassaforma",
      postazione: "In prossimità lavorazione",
      ta: 25.3,
      va: 0.35,
      ur: 65.1,
      tnw: 23.5,
      trugiada: 20.8,
      tg: 25.1,
    },
    {
      id: "galleriaInverno-r9",
      codice: "MCR10",
      data: "20/12/2024",
      fase: "Allungamento impianto di ventilazione",
      postazione: "In prossimità lavorazione",
      ta: 25.2,
      va: 0.31,
      ur: 65.6,
      tnw: 23.3,
      trugiada: 21.0,
      tg: 25.7,
    },
    {
      id: "galleriaInverno-r10",
      codice: "MCR09",
      data: "20/02/2025",
      fase: "Attività in officina",
      postazione: "Officina",
      ta: 25.2,
      va: 0.31,
      ur: 65.6,
      tnw: 23.3,
      trugiada: 21.0,
      tg: 25.7,
    },
  ],
  lavorazioni: [
    {
      id: "galleriaInverno-l1",
      fase: "Perforazione del fronte per consolidamento",
      mansioni: [
        "galleriaInverno-m1",
        "galleriaInverno-m2",
        "galleriaInverno-m3",
        "galleriaInverno-m4",
        "galleriaInverno-m5",
        "galleriaInverno-m6",
      ],
      met: 2.2,
      rilievo: "galleriaInverno-r1",
    },
    {
      id: "galleriaInverno-l2",
      fase: "Scavo/Disgaggio",
      mansioni: [
        "galleriaInverno-m7",
        "galleriaInverno-m8",
        "galleriaInverno-m9",
        "galleriaInverno-m10",
        "galleriaInverno-m11",
        "galleriaInverno-m12",
      ],
      met: 1.4,
      rilievo: "galleriaInverno-r2",
    },
    {
      id: "galleriaInverno-l3",
      fase: "Scavo/Disgaggio",
      mansioni: ["galleriaInverno-m13", "galleriaInverno-m10"],
      met: 2.4,
      rilievo: "galleriaInverno-r2",
    },
    {
      id: "galleriaInverno-l4",
      fase: "Smarino",
      mansioni: [
        "galleriaInverno-m14",
        "galleriaInverno-m9",
        "galleriaInverno-m15",
        "galleriaInverno-m16",
        "galleriaInverno-m10",
        "galleriaInverno-m17",
        "galleriaInverno-m18",
        "galleriaInverno-m19",
      ],
      met: 1.4,
      rilievo: "galleriaInverno-r3",
    },
    {
      id: "galleriaInverno-l5",
      fase: "Smarino",
      mansioni: [
        "galleriaInverno-m20",
        "galleriaInverno-m21",
        "galleriaInverno-m22",
        "galleriaInverno-m8",
        "galleriaInverno-m13",
        "galleriaInverno-m23",
        "galleriaInverno-m24",
        "galleriaInverno-m25",
        "galleriaInverno-m26",
      ],
      met: 2.4,
      rilievo: "galleriaInverno-r3",
    },
    {
      id: "galleriaInverno-l6",
      fase: "Posa centina",
      mansioni: [
        "galleriaInverno-m14",
        "galleriaInverno-m9",
        "galleriaInverno-m15",
        "galleriaInverno-m16",
        "galleriaInverno-m10",
      ],
      met: 2.4,
      rilievo: "galleriaInverno-r4",
    },
    {
      id: "galleriaInverno-l7",
      fase: "Posa centina",
      mansioni: [
        "galleriaInverno-m8",
        "galleriaInverno-m13",
        "galleriaInverno-m24",
        "galleriaInverno-m25",
        "galleriaInverno-m26",
      ],
      met: 1.4,
      rilievo: "galleriaInverno-r4",
    },
    {
      id: "galleriaInverno-l8",
      fase: "Carpenteria in cassaforma",
      mansioni: [
        "galleriaInverno-m27",
        "galleriaInverno-m28",
        "galleriaInverno-m29",
        "galleriaInverno-m30",
        "galleriaInverno-m31",
        "galleriaInverno-m32",
        "galleriaInverno-m33",
        "galleriaInverno-m34",
        "galleriaInverno-m35",
        "galleriaInverno-m36",
      ],
      met: 2.8,
      rilievo: "galleriaInverno-r5",
    },
    {
      id: "galleriaInverno-l9",
      fase: "Spritz",
      mansioni: [
        "galleriaInverno-m14",
        "galleriaInverno-m15",
        "galleriaInverno-m16",
        "galleriaInverno-m11",
        "galleriaInverno-m17",
        "galleriaInverno-m37",
        "galleriaInverno-m38",
      ],
      met: 2.2,
      rilievo: "galleriaInverno-r6",
    },
    {
      id: "galleriaInverno-l10",
      fase: "Spritz",
      mansioni: [
        "galleriaInverno-m23",
        "galleriaInverno-m24",
        "galleriaInverno-m19",
      ],
      met: 1.4,
      rilievo: "galleriaInverno-r6",
    },
    {
      id: "galleriaInverno-l11",
      fase: "Manutenzione mezzi - camerone",
      mansioni: ["galleriaInverno-m39", "galleriaInverno-m40"],
      met: 2.8,
      rilievo: "galleriaInverno-r7",
    },
    {
      id: "galleriaInverno-l12",
      fase: "Manutenzione straordinaria mezzi – dietro cassaforma",
      mansioni: ["galleriaInverno-m39", "galleriaInverno-m40"],
      met: 2.8,
      rilievo: "galleriaInverno-r8",
    },
    {
      id: "galleriaInverno-l13",
      fase: "Attività di officina",
      mansioni: ["galleriaInverno-m39", "galleriaInverno-m41"],
      met: 2.4,
      rilievo: "galleriaInverno-r10",
    },
    {
      id: "galleriaInverno-l14",
      fase: "Allungamento impianto di ventilazione",
      mansioni: ["galleriaInverno-m39", "galleriaInverno-m40"],
      met: 2.8,
      rilievo: "galleriaInverno-r9",
    },
  ],
};

export const GALLERIA_ESTATE: Scenario = {
  mansioni: [
    { id: "galleriaEstate-m1", nome: "Perforatore" },
    { id: "galleriaEstate-m2", nome: "Capo cantiere" },
    { id: "galleriaEstate-m3", nome: "Capo imbocco – Assistente" },
    { id: "galleriaEstate-m4", nome: "Caposquadra Minatore" },
    { id: "galleriaEstate-m5", nome: "Escavatorista- Escavatorista Palista" },
    { id: "galleriaEstate-m6", nome: "Palista-autista" },
    { id: "galleriaEstate-m7", nome: "Capo imbocco - Assistente" },
    { id: "galleriaEstate-m8", nome: "Palista – Autista" },
    { id: "galleriaEstate-m9", nome: "Autista – Minatore" },
    { id: "galleriaEstate-m10", nome: "Lancista -Autista" },
    { id: "galleriaEstate-m11", nome: "Fochino- Autista" },
    { id: "galleriaEstate-m12", nome: "Jumbista - Autista" },
    { id: "galleriaEstate-m13", nome: "Capo imbocco/ Assistente" },
    { id: "galleriaEstate-m14", nome: "Lancista" },
    { id: "galleriaEstate-m15", nome: "Autista/Minatore" },
    { id: "galleriaEstate-m16", nome: "Escavatorista - Escavatorista/Palista" },
    {
      id: "galleriaEstate-m17",
      nome: "Caposquadra Carpentiere/Carpentiere/Ferraiolo",
    },
    { id: "galleriaEstate-m18", nome: "Addetto ripristini NC" },
    {
      id: "galleriaEstate-m19",
      nome: "Meccanico di galleria, Elettricista di galleria",
    },
    { id: "galleriaEstate-m20", nome: "Capo officina/meccanico/saldatore" },
    { id: "galleriaEstate-m21", nome: "Capo elettricista/elettricista" },
  ],
  rilievi: [
    {
      id: "galleriaEstate-r1",
      codice: "MCR01",
      data: "13/06/2025",
      fase: "Consolidamento del fronte",
      postazione: "In prossimità",
      ta: 34.2,
      va: 0.72,
      ur: 65.4,
      tnw: 28.6,
      trugiada: 27.0,
      tg: 32.4,
    },
    {
      id: "galleriaEstate-r2",
      codice: "MCR02",
      data: "13/06/2025",
      fase: "Armatura calotta",
      postazione: "In prossimità",
      ta: 33.4,
      va: 0.51,
      ur: 68.6,
      tnw: 28.7,
      trugiada: 27.2,
      tg: 31.5,
    },
    {
      id: "galleriaEstate-r3",
      codice: "MCR03",
      data: "13/06/2025",
      fase: "Manutenzione mezzi",
      postazione: "In prossimità",
      ta: 34.0,
      va: 0.35,
      ur: 70.3,
      tnw: 29.3,
      trugiada: 28.1,
      tg: 32.2,
    },
    {
      id: "galleriaEstate-r4",
      codice: "MCR04",
      data: "30/07/2025",
      fase: "Scavo",
      postazione: "A terra",
      ta: 31.1,
      va: 1.7,
      ur: 66.4,
      tnw: 25.8,
      trugiada: 24.5,
      tg: 30.1,
    },
    {
      id: "galleriaEstate-r5",
      codice: "MCR05",
      data: "30/07/2025",
      fase: "Impermeabilizzazione calotta",
      postazione: "In prossimità",
      ta: 32.7,
      va: 0.62,
      ur: 70.2,
      tnw: 27.8,
      trugiada: 27.1,
      tg: 30.5,
    },
    {
      id: "galleriaEstate-r6",
      codice: "MCR06",
      data: "11/09/2025",
      fase: "Carpenteria in cassaforma",
      postazione: "In prossimità",
      ta: 28.6,
      va: 0.68,
      ur: 69.4,
      tnw: 23.6,
      trugiada: 22.5,
      tg: 29.7,
    },
    {
      id: "galleriaEstate-r7",
      codice: "MCR07",
      data: "11/09/2025",
      fase: "Smarino",
      postazione: "A terra",
      ta: 32.1,
      va: 0.51,
      ur: 59.8,
      tnw: 25.2,
      trugiada: 23.6,
      tg: 31.7,
    },
    {
      id: "galleriaEstate-r8",
      codice: "MCR09",
      data: "11/09/2025",
      fase: "Posa centina",
      postazione: "A terra",
      ta: 30.4,
      va: 1.1,
      ur: 60.8,
      tnw: 23.7,
      trugiada: 22.0,
      tg: 30.0,
    },
  ],
  lavorazioni: [
    {
      id: "galleriaEstate-l1",
      fase: "Consolidamento del fronte",
      mansioni: ["galleriaEstate-m1"],
      met: 2.2,
      rilievo: "galleriaEstate-r1",
    },
    {
      id: "galleriaEstate-l2",
      fase: "Scavo",
      mansioni: ["galleriaEstate-m2", "galleriaEstate-m3", "galleriaEstate-m4"],
      met: 1.8,
      rilievo: "galleriaEstate-r4",
    },
    {
      id: "galleriaEstate-l3",
      fase: "Scavo",
      mansioni: ["galleriaEstate-m5", "galleriaEstate-m6"],
      met: 2.2,
      rilievo: "galleriaEstate-r4",
    },
    {
      id: "galleriaEstate-l4",
      fase: "Smarino",
      mansioni: ["galleriaEstate-m2", "galleriaEstate-m7"],
      met: 1.8,
      rilievo: "galleriaEstate-r7",
    },
    {
      id: "galleriaEstate-l5",
      fase: "Smarino",
      mansioni: [
        "galleriaEstate-m8",
        "galleriaEstate-m9",
        "galleriaEstate-m10",
        "galleriaEstate-m11",
        "galleriaEstate-m12",
      ],
      met: 2.2,
      rilievo: "galleriaEstate-r7",
    },
    {
      id: "galleriaEstate-l6",
      fase: "Posa centina",
      mansioni: ["galleriaEstate-m13", "galleriaEstate-m2"],
      met: 1.8,
      rilievo: "galleriaEstate-r8",
    },
    {
      id: "galleriaEstate-l7",
      fase: "Posa centina",
      mansioni: [
        "galleriaEstate-m14",
        "galleriaEstate-m15",
        "galleriaEstate-m16",
        "galleriaEstate-m4",
      ],
      met: 2.8,
      rilievo: "galleriaEstate-r8",
    },
    {
      id: "galleriaEstate-l8",
      fase: "Armatura calotta",
      mansioni: [
        "galleriaEstate-m2",
        "galleriaEstate-m17",
        "galleriaEstate-m18",
      ],
      met: 2.8,
      rilievo: "galleriaEstate-r2",
    },
    {
      id: "galleriaEstate-l9",
      fase: "Carpenteria in cassaforma",
      mansioni: [
        "galleriaEstate-m2",
        "galleriaEstate-m17",
        "galleriaEstate-m18",
      ],
      met: 2.8,
      rilievo: "galleriaEstate-r6",
    },
    {
      id: "galleriaEstate-l10",
      fase: "Manutenzione mezzi",
      mansioni: [
        "galleriaEstate-m19",
        "galleriaEstate-m20",
        "galleriaEstate-m21",
      ],
      met: 2.4,
      rilievo: "galleriaEstate-r3",
    },
    {
      id: "galleriaEstate-l11",
      fase: "Impermeabilizzazione calotta",
      mansioni: [
        "galleriaEstate-m2",
        "galleriaEstate-m17",
        "galleriaEstate-m18",
      ],
      met: 2.8,
      rilievo: "galleriaEstate-r5",
    },
  ],
};

export const ESTERNO_ESTATE: Scenario = {
  mansioni: [
    { id: "esternoEstate-m1", nome: "Autista piazzale esterno" },
    { id: "esternoEstate-m2", nome: "Operatore mezzi-Gruista" },
    { id: "esternoEstate-m3", nome: "Addetto apprestamenti di sicurezza" },
    { id: "esternoEstate-m4", nome: "Magazziniere" },
    { id: "esternoEstate-m5", nome: "Addetto guardiania" },
    { id: "esternoEstate-m6", nome: "Tutte le mansioni" },
    { id: "esternoEstate-m7", nome: "Addetto impianto di depurazione" },
    { id: "esternoEstate-m8", nome: "Addetto frantoio-Ribaltina-nastro" },
    {
      id: "esternoEstate-m9",
      nome: "Capo elettricista/ Elettricista/ Elettricista di galleria",
    },
    {
      id: "esternoEstate-m10",
      nome: "Capo officina / Meccanico/ Saldatore, fabbro",
    },
    { id: "esternoEstate-m11", nome: "Addetti piazzale centine" },
    { id: "esternoEstate-m12", nome: "Addetto distributore gasolio" },
  ],
  rilievi: [],
  lavorazioni: [
    {
      id: "esternoEstate-l1",
      fase: "Trasporto materiali di cantiere",
      mansioni: ["esternoEstate-m1"],
      met: 2.2,
    },
    {
      id: "esternoEstate-l2",
      fase: "Movimentazione materiali di cantiere",
      mansioni: ["esternoEstate-m2"],
      met: 2.2,
    },
    {
      id: "esternoEstate-l3",
      fase: "Verifica apprestamenti di sicurezza",
      mansioni: ["esternoEstate-m3"],
      met: 1.4,
    },
    {
      id: "esternoEstate-l4",
      fase: "Gestione magazzino Ricevimento merci",
      mansioni: ["esternoEstate-m4"],
      met: 1.4,
    },
    {
      id: "esternoEstate-l5",
      fase: "Controllo accessi",
      mansioni: ["esternoEstate-m5"],
      met: 1.4,
    },
    {
      id: "esternoEstate-l6",
      fase: "Attività ordinarie in esterno",
      mansioni: ["esternoEstate-m6"],
      met: 2.2,
    },
    {
      id: "esternoEstate-l7",
      fase: "Supervisione/Conduzione impianto di depurazione",
      mansioni: ["esternoEstate-m7"],
      met: 1.8,
    },
    {
      id: "esternoEstate-l8",
      fase: "Verifica/interventi su nastro trasportatore dello smarino e su frantoio",
      mansioni: ["esternoEstate-m8"],
      met: 1.8,
    },
    {
      id: "esternoEstate-l9",
      fase: "Interventi di manutenzione mezzi",
      mansioni: ["esternoEstate-m9", "esternoEstate-m10"],
      met: 2.4,
    },
    {
      id: "esternoEstate-l10",
      fase: "Pre-assemblaggio e movimentazione centine",
      mansioni: ["esternoEstate-m2", "esternoEstate-m11"],
      met: 2.8,
    },
    {
      id: "esternoEstate-l11",
      fase: "Distribuzione carburante",
      mansioni: ["esternoEstate-m12"],
      met: 2.2,
    },
  ],
};

export const ESTERNO_INVERNO: Scenario = {
  mansioni: [
    {
      id: "esternoInverno-m1",
      nome: "CSQ Carpentiere/Carpentiere/Aiuto Carpentiere/Carpentiere muratore",
    },
    { id: "esternoInverno-m2", nome: "Ferraiolo/Aiuto ferraiolo" },
    { id: "esternoInverno-m3", nome: "Pompista" },
    { id: "esternoInverno-m4", nome: "Addetto Jet Grouting" },
    { id: "esternoInverno-m5", nome: "Addetto alla perforazione" },
    { id: "esternoInverno-m6", nome: "Impiantista" },
    { id: "esternoInverno-m7", nome: "Meccanico" },
    { id: "esternoInverno-m8", nome: "Moviere" },
    { id: "esternoInverno-m9", nome: "Tutte le mansioni" },
  ],
  rilievi: [],
  lavorazioni: [
    {
      id: "esternoInverno-l1",
      fase: "Casserature, carpenteria, disarmo e opere murarie",
      mansioni: ["esternoInverno-m1"],
      met: 2.8,
    },
    {
      id: "esternoInverno-l2",
      fase: "Taglio, piegatura, assemblaggio e posa armature",
      mansioni: ["esternoInverno-m2"],
      met: 2.8,
    },
    {
      id: "esternoInverno-l3",
      fase: "Pompaggio calcestruzzo, posizionamento tubazioni e pulizia pompa",
      mansioni: ["esternoInverno-m3"],
      met: 2.2,
    },
    {
      id: "esternoInverno-l4",
      fase: "Esecuzione colonne jet grouting e movimentazione tubi/attrezzature",
      mansioni: ["esternoInverno-m4"],
      met: 2.4,
    },
    {
      id: "esternoInverno-l5",
      fase: "Esecuzione di perforazioni",
      mansioni: ["esternoInverno-m5"],
      met: 2.0,
    },
    {
      id: "esternoInverno-l6",
      fase: "Installazione e manutenzione impianti di cantiere",
      mansioni: ["esternoInverno-m6"],
      met: 2.4,
    },
    {
      id: "esternoInverno-l7",
      fase: "Manutenzione mezzi d’opera e attrezzature",
      mansioni: ["esternoInverno-m7"],
      met: 2.8,
    },
    {
      id: "esternoInverno-l8",
      fase: "Regolazione del traffico e assistenza alle manovre",
      mansioni: ["esternoInverno-m8"],
      met: 1.4,
    },
    {
      id: "esternoInverno-l9",
      fase: "Attività ordinarie in esterno",
      mansioni: ["esternoInverno-m9"],
      met: 2.2,
    },
  ],
};

export const MESI_ESTATE_CTG: MeseMeteo[] = [
  { mese: "Giugno", ta: 23.1, ur: 72.4, va: 0.8, tr: 29.1 },
  { mese: "Luglio", ta: 26.5, ur: 71.4, va: 1.1, tr: 33.2 },
  { mese: "Agosto", ta: 26.2, ur: 67.2, va: 1.2, tr: 33.1 },
];

export const PICCO_ESTATE_CTG = {
  data: "11 agosto 2025",
  ta: 38,
  ur: 55,
  va: 0,
  tg: 40,
  tnw: 28,
};

export const MESI_INVERNO_XENIA: MeseMeteo[] = [
  {
    mese: "Dicembre",
    ta: 12.8,
    ur: 72.8,
    va: 2.1,
    peggiore: { ta: 3, ur: 82, va: 7.2 },
  },
  {
    mese: "Gennaio",
    ta: 12.3,
    ur: 74.7,
    va: 2.5,
    peggiore: { ta: -2, ur: 53, va: 7.2 },
  },
  {
    mese: "Febbraio",
    ta: 13.3,
    ur: 74.1,
    va: 2.6,
    peggiore: { ta: 3, ur: 70, va: 8.1 },
  },
];
