/** Catalogo delle attività del DVR Posture Castagnola 2025 (capitoli 5 e 6), con i codici OWAS e le classi riportate nel modello. */
import type { AttivitaCatalogo } from '../valutazione'

export const CATALOGO_CASTAGNOLA: (AttivitaCatalogo & { classiModello: number[] })[] = [
  {
    gruppo: "Consolidamento del fronte",
    fase: "Consolidamento del fronte",
    attivita: "Posizionamento macchina per il consolidamento",
    descrizione: "L’operazione consiste nel posizionare la macchina al fronte e collegarla alle varie alimentazioni (acqua, elettricità, cls). La squadra del consolidamento è impegnata a terra in piedi con le braccia tese, talvolta ci si può posizionare in ginocchio con le braccia piegate per alcuni collegamenti e la schiena piegata.",
    rischio: "Posture incongrue",
    mansioni: "Perforatore / Disgaggiatore/Perforatore Assistente perforatore Impiantista/Perforatore Responsabile Consolidamenti",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }, { schiena: 2, braccia: 1, gambe: 6, carico: 1 }],
    classiModello: [1, 2],
  },
  {
    gruppo: "Consolidamento del fronte",
    fase: "Consolidamento del fronte",
    attivita: "Perforazioni per il consolidamento",
    descrizione: "L’attività consiste nel guidare i bracci della macchina per il consolidamento per effettuare i fori nel fronte. Il Csq. Perforatore, si posiziona in prossimità del fronte in piedi con la schiena dritta, le braccia piegate e le mani sul joystick dei comandi per guidare i bracci.",
    rischio: "Posture incongrue",
    mansioni: "Perforatore / Disgaggiatore/Perforatore Assistente perforatore Impiantista/Perforatore Responsabile Consolidamenti",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Consolidamento del fronte",
    fase: "Consolidamento del fronte",
    attivita: "Posa in opera dei tubi in VTR",
    descrizione: "L’ attività manuale consiste nel sollevare i tubi da terra e posizionarli sul braccio del perforatore; quest’ultimo è regolabile in altezza e quindi viene posizionato ad un’altezza di circa 70 cm da terra evitando così ai lavoratori ulteriori sollevamenti (il chiodo pesa circa tra i 10 e i 20 Kg); Gli operatori partendo da una posizione di schiena curva, braccia sotto le spalle e gambe piegate sollevano il tubo sino a circa 70 cm da terra con una postura di schiena dritta, gambe distese e braccia sotto il livello delle spalle.",
    rischio: "Movimentazione manuale dei carichi / Posture incongrue",
    mansioni: "Perforatore / Disgaggiatore/Perforatore Assistente perforatore Impiantista/Perforatore Responsabile Consolidamenti",
    posture: [{ schiena: 2, braccia: 1, gambe: 6, carico: 2 }, { schiena: 1, braccia: 1, gambe: 2, carico: 2 }],
    classiModello: [2, 1],
  },
  {
    gruppo: "Consolidamento del fronte",
    fase: "Consolidamento del fronte",
    attivita: "Iniezioni in cls",
    descrizione: "La lavorazione consiste nell’iniettare a mezzo di tubi e valvole il cls nel foro al fronte in cui è stato inserito il chiodo in VTR. L’impiantista coordina l’impianto di cls stando in piedi con le gambe distese e la schiena dritta e le braccia sotto il livello delle spalle per guidare i comandi dell’impianto.",
    rischio: "Posture incongrue",
    mansioni: "Perforatore / Disgaggiatore/Perforatore Assistente perforatore Impiantista/Perforatore Responsabile Consolidamenti",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Consolidamento del fronte",
    fase: "Consolidamento del fronte",
    attivita: "Preparazioni tubi e operazioni ordinarie",
    descrizione: "L’operazione consiste nel trasporto in galleria dei tubi in vtr. I chiodi legati in fasci con delle imbragature vengono trasportati sino al fronte per mezzo di un sollevatore telescopico, e una volta appoggiati a terra l’operatore provvede a slegare il fascio di tubi. L’ operatore sarà seduto sul sedile del mezzo, con le mani sui comandi del mezzo, la schiena diritta o leggermente curva.",
    rischio: "Posture incongrue",
    mansioni: "Perforatore / Disgaggiatore/Perforatore Assistente perforatore Impiantista/Perforatore Responsabile Consolidamenti",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }, { schiena: 2, braccia: 1, gambe: 1, carico: 1 }, { schiena: 2, braccia: 1, gambe: 6, carico: 2 }],
    classiModello: [1, 2, 2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Perforazione del fronte",
    attivita: "Perforazione del fronte",
    descrizione: "L’operazione consiste nella perforazione del fronte per il successivo caricamento della volata. L’attività viene svolta tramite il jumbo. Il jumbista, insieme eventualmente ad un minatore esegue la perforazione dall’interno della macchina, in posizione in piedi, con le braccia sui comandi della macchina e la schiena, generalmente diritta.",
    rischio: "Vibrazioni / sul corpo intero / Posture incongrue",
    mansioni: "Jumbista/Minatore / Fochino/Minatore/Gruista",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Caricamento della volata",
    attivita: "Scarico delle casse di esplosivo",
    descrizione: "L’operazione consiste nello spostamento delle casse di esplosivo dal furgone al fronte di scavo. Il lavoratore, in posizione di schiena dritta e gambe distese, in piedi scarica la merce con braccia entrambe sollevate sopra la linea delle spalle, rimanendo in posizione in piedi, schiena dritta ma stavolta con le braccia sotto la linea delle spalle trasporta le scatole fino al punto di stoccaggio, il peso trasportato è di circa 25 kg. Talvolta è possibile che egli si trova in posizione di schiena curva in ginocchio su uno o due ginocchia con le braccia al di sotto del livello delle spalle.",
    rischio: "Movimentazione manuale / dei carichi",
    mansioni: "Lancista/autista / Lancista/Autista/Minatore / Fochino/Minatore/Mulettista/Autista / Minatore",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 3 }, { schiena: 1, braccia: 3, gambe: 2, carico: 3 }, { schiena: 2, braccia: 1, gambe: 6, carico: 1 }],
    classiModello: [1, 1, 2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Caricamento della volata",
    attivita: "Posizionamento candelotti",
    descrizione: "L’operazione consiste nel posizionamento, uno per uno, dei candelotti di esplosivo nei fori precedentemente praticati sul fronte con il jumbo. L’operatore che svolge l’operazione è in piedi sul cestello, le braccia in avanti all’altezza del torace, la schiena leggermente curva in avanti.",
    rischio: "Posture incongrue",
    mansioni: "Lancista/autista / Lancista/Autista/Minatore / Fochino/Minatore/Mulettista/Autista / Minatore",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }, { schiena: 2, braccia: 3, gambe: 2, carico: 1 }],
    classiModello: [2, 3],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Scavo",
    attivita: "Scavo del fronte",
    descrizione: "L’operazione consiste nello scavo e contemporaneo smarino del fronte e viene eseguita dall’escavatorista che esegue anche il disgaggio del fronte. / L’escavatorista è seduto sul sedile dell’escavatore, con le mani sui comandi del mezzo, la schiena diritta o leggermente curva.",
    rischio: "Vibrazioni / sul corpo intero / Posture incongrue",
    mansioni: "Escavatorista/ palista/Lancista / Escavatorista/Palista / Escavatorista/Palista/Mulettista / Escavatorista/Autista/Mulettista/Palista",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }, { schiena: 2, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1, 2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Scavo",
    attivita: "Assistenza allo scavo",
    descrizione: "Durante l’esecuzione dello scavo può essere presente al fronte un assistente che esegue la bagnatura dello del fronte e del materiale scavato o altre attività di supporto. / L’assistenza viene eseguita da un operatore in posizione in piedi con le mani che possono sorreggere la lancia per la bagnatura del terreno, con la schiena diritta.",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore/Caposquadra/Lancista / Minatore",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Smarino",
    attivita: "Smarino del fronte",
    descrizione: "L’attività consiste nel portare fuori dalla galleria la roccia proveniente dal fronte su cui è avvenuta la volata o il disgaggio. / Il palista, a bordo della pala, carica la terra/roccia su dei dumper che portano fuori il materiale. / Il palista esegue l’operazione in posizione seduta, con le mani sui comandi del mezzo e la schiena diritta o leggermente curva.",
    rischio: "Vibrazioni / sul corpo intero / Posture incongrue",
    mansioni: "Escavatorista/Palista / Escavatorista/Autista/Mulettista/Palista",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }, { schiena: 2, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1, 2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Smarino",
    attivita: "Trasporto terra dello smarino",
    descrizione: "L’attività consiste nel portare fuori dalla galleria la roccia proveniente dal fronte su cui è avvenuto lo scavo. / L’autista dell’autocarro, a bordo del mezzo, trasporta fuori il materiale. / L’autista esegue l’operazione in posizione seduta, con le mani sui manubri del mezzo e la schiena diritta o leggermente curva",
    rischio: "Vibrazioni / sul corpo intero / Posture incongrue",
    mansioni: "Autista/Minatore / Autista/Minatore/Gruista / Lancista/Autista/Minatore / Autista/Minatore/Mulettista",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }, { schiena: 2, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1, 2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Smarino",
    attivita: "Assistenza allo smarino",
    descrizione: "Durante l’esecuzione dello scavo e dello smarino può essere presente al fronte un assistente che esegue la bagnatura dello del fronte e del materiale scavato o altre attività di supporto. / L’assistenza viene eseguita da un operatore in posizione in piedi con le mani che possono sorreggere la lancia per la bagnatura del terreno, con la schiena diritta",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore/Caposquadra/Lancista / Minatore",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Pre-Spritz –  / Spritz",
    attivita: "Avvicinamento/ allontanamento macchina spritz",
    descrizione: "L’operazione consiste nella movimentazione della macchina spritz per posizionarla al fronte o allontanarla dal fronte. / Il lancista, che esegue l’operazione, è in posizione seduta, con le mani sui comandi del mezzo, la schiena curva e in torsione per seguire meglio il tragitto del mezzo",
    rischio: "Posture incongrue",
    mansioni: "Lancista/Mulettista / Lancista/Autista/Mulettista / Lancista/Autista / Aiuto Lancista / Lancista/Autista/Palista",
    posture: [{ schiena: 4, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Pre-Spritz –  / Spritz",
    attivita: "Spritz – / pre spritz",
    descrizione: "Il lancista nello svolgere l’operazione è in posizione in piedi, con le mani sui comandi della lancia, la schiena diritta, la testa rivolta verso l’alto. Nell’eseguire lo spritz, il lancista sostiene, tramite una tracolla, i comandi della pompa",
    rischio: "Posture incongrue / Movimentazione manuale / dei carichi",
    mansioni: "Lancista/Mulettista / Lancista/Autista/Mulettista / Lancista/Autista / Aiuto Lancista / Lancista/Autista/Palista",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Pre-Spritz –  / Spritz",
    attivita: "Assistenza Spritz – pre-spritz",
    descrizione: "Durante l’attività di spritz il lancista può ricevere l’assistenza di un minatore che, generalmente esegue l’attività di assistenza nell’area del fronte o in tramoggia. Nell’eseguire l’assistenza al lancista, il minatore è in piedi, con le braccia distese e la schiena diritta",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Pre-Spritz –  / Spritz",
    attivita: "Pulizia tubo pompa spritz",
    descrizione: "Al termine dell’attività di spritz o di pre-spritz la pompa viene pulita del cls che può essere rimasto attaccato alle pareti, facendo passare ripetutamente una palla di spugna attraverso il tubo. L’operazione viene svolta dal lancista insieme ad uno dei minatori stando in piedi, con le braccia distese e la schiena generalmente curva",
    rischio: "Posture incongrue",
    mansioni: "Lancista/Autista/Mulettista / Lancista/Autista/Minatore / Lancista/Mulettista / Lancista/Autista / Aiuto Lancista / Lancista/Autista/Palista",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Posa centina",
    attivita: "Posa centine tramite mezzo sollevatore",
    descrizione: "L’operazione prevede il posizionamento della centina agganciata alla pinza del mezzo sollevatore. / L’autista è in piedi sulla piazzola di comando del mezzo, con le mani sui comandi del mezzo, la schiena diritta o leggermente curva in avanti per seguire l’operazione di posizionamento della centina.",
    rischio: "Vibrazioni sul corpo intero / Posture incongrue",
    mansioni: "Minatore / Minatore/Caposquadra/ / Lancista / Aiuto Lancista/Minatore",
    posture: [{ schiena: 2, braccia: 1, gambe: 1, carico: 1 }, { schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2, 1],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Posa centina",
    attivita: "Posa centine tramite escavatore/pala con pinza",
    descrizione: "L’operazione prevede il posizionamento della centina agganciata alla pinza dell’escavatore/pala. / L’escavatorista/palista è seduto all’interno del mezzo, con le mani sui comandi del mezzo, la schiena diritta o leggermente curva in avanti per seguire l’operazione di posizionamento della centina.",
    rischio: "Vibrazioni sul corpo intero / Posture incongrue",
    mansioni: "Escavatorista/Palista / Escavatorista/Palista/Mulettista / Escavatorista/Autista/Mulettista/Palista",
    posture: [{ schiena: 2, braccia: 1, gambe: 1, carico: 1 }, { schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [2, 1],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Posa centina",
    attivita: "Posa centine - assistenza a terra",
    descrizione: "L’operazione prevede il posizionamento della centina agganciata alla pinza del mezzo sollevatore. / L’operatore che esegue l’assistenza da terra è in piedi con le braccia distese, la schiena per parte del tempo dritta e per parte del tempo curva per seguire l’operazione di posizionamento della centina e dare indicazioni all’addetto preposto alla guida del mezzo sollevatore.",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }, { schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1, 2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Posa centina",
    attivita: "Montaggio delle catene",
    descrizione: "L’operazione prevede il montaggio delle catene di collegamento tra le centine. / L’operatore che svolge l’operazione è in piedi sul cestello, le braccia protese verso l’alto per sostenere le catene ed eseguirne il montaggio, la schiena curva ed in torsione.",
    rischio: "Movimentazione manuale dei carichi / Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Escavatorista/Palista / Escavatorista/Palista/Mulettista",
    posture: [{ schiena: 4, braccia: 3, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Posa centina",
    attivita: "Montaggio dei piedi della centina",
    descrizione: "L’operazione prevede il montaggio della parte più bassa della centina da terra. / L’operatore che svolge l’operazione è in piedi, con le braccia sotto il livello delle spalle e la schiena curva.",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Escavatorista/Palista / Escavatorista/Palista/Mulettista",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Posa centina",
    attivita: "Verifica del corretto posizionamento della centina",
    descrizione: "L’operazione prevede il controllo dell’effettivo montaggio della parte più bassa della centina da terra. / L’operatore che svolge l’operazione è in piedi, con le braccia sotto il livello delle spalle e la schiena curva.",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Escavatorista/Palista / Escavatorista/Palista/Mulettista",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Avanzamento (scavo con volata e con martellone)",
    fase: "Posa centina",
    attivita: "Posizionamento e montaggio della rete elettrosaldata e delle catene",
    descrizione: "L’operazione del montaggio della rete elettrosaldata e delle catene viene eseguita da bordo di un cestello montato su un sollevatore telescopico. / L’autista del sollevatore è seduto sul sedile del sollevatore telescopico, con le mani sui comandi del mezzo, la schiena diritta o leggermente curva in avanti per seguire l’operazione di posizionamento e montaggio della rete elettrosaldata e delle catene",
    rischio: "Vibrazioni sul corpo intero / Posture incongrue / Movimentazione manuale dei carichi",
    mansioni: "Caposquadra/Minatore / Minatore / Escavatorista/Palista / Escavatorista/Palista/Mulettista",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }, { schiena: 2, braccia: 3, gambe: 1, carico: 1 }, { schiena: 1, braccia: 3, gambe: 2, carico: 2 }, { schiena: 4, braccia: 3, gambe: 2, carico: 2 }],
    classiModello: [1, 3, 1, 3],
  },
  {
    gruppo: "Getto murette",
    fase: "Armatura murette",
    attivita: "Preparazione ferri o gabbie d’armatura",
    descrizione: "L’operazione consiste nella preparazione dei ferri d’armatura da riporre all’interno delle murette scavate. L’operazione viene eseguita fuori dalle murette, all’interno o all’esterno della galleria, e consiste generalmente nel legare insieme più ferri ancor prima di posizionarli nelle murette. / L’attività è svolta dal carpentiere murette in posizione in piedi con le gambe piegate o in ginocchio su una delle due ginocchia, le mani all’altezza del torace e la schiena curva. L’attività può prevedere che il carpentiere sostenga delle attrezzature (martello, tenaglia, ecc.)",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Ferraiolo / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 2, braccia: 1, gambe: 4, carico: 1 }, { schiena: 2, braccia: 1, gambe: 6, carico: 1 }],
    classiModello: [3, 2],
  },
  {
    gruppo: "Getto murette",
    fase: "Armatura murette",
    attivita: "Montaggio ferri o gabbie d’armatura",
    descrizione: "L’operazione consiste nel montaggio dei ferri d’armatura all’interno delle murette scavate. / L’attività è svolta dal carpentiere murette in posizione in piedi con le gambe diritte oppure piegate oppure in ginocchio, le mani all’altezza del torace e la schiena curva. L’attività può prevedere che il carpentiere sostenga delle attrezzature (martello, tenaglia, ecc.)",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Ferraiolo / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }, { schiena: 2, braccia: 1, gambe: 6, carico: 1 }, { schiena: 2, braccia: 1, gambe: 4, carico: 1 }],
    classiModello: [2, 2, 3],
  },
  {
    gruppo: "Getto murette",
    fase: "Casseratura murette",
    attivita: "Messa in opera della cassaforma",
    descrizione: "L’operazione consiste nel posizionamento della cassaforma delle murette tramite sollevatore telescopico. / L’operatore alla guida del sollevatore è seduto sul sedile del sollevatore telescopico, con le mani sui comandi del mezzo, la schiena diritta o curva in avanti per seguire l’operazione di posizionamento della cassaforma",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Ferraiolo / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }, { schiena: 2, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1, 2],
  },
  {
    gruppo: "Getto murette",
    fase: "Casseratura murette",
    attivita: "Messa in opera della cassaforma – assistenza a terra",
    descrizione: "Durante il posizionamento della cassaforma, il carpentiere da terra segue l’attività e dà indicazioni all’autista sul corretto posizionamento del cassero. Il carpentiere è in posizione eretta con gambe e braccia distese e la schiena in diverse posizioni (dritta o curva o curva e in torsione)",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Ferraiolo / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }, { schiena: 2, braccia: 1, gambe: 2, carico: 1 }, { schiena: 4, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1, 2, 2],
  },
  {
    gruppo: "Getto murette",
    fase: "Getto delle murette",
    attivita: "Getto cls",
    descrizione: "L’operazione prevede il getto del cls per la realizzazione delle murette. Dall’autobetoniera il cls viene riversato nelle murette tramite uno scivolo. Il carpentiere assiste all’operazione stando in posizione in piedi, con le braccia distese e la schiena diritta",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Ferraiolo / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Getto murette",
    fase: "Getto delle murette",
    attivita: "Vibratura Cls",
    descrizione: "L’operazione consiste nella vibrazione del calcestruzzo per garantirne l’omogeneità e la compattezza. L’operatore durante la fase lavorativa e in piedi con le braccia sotto il livello delle spalle, solleva un peso inferiore a 10Kg quando sorregge il vibratore e può avere la schiena curva",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Ferraiolo / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Armatura e getto della calotta",
    fase: "Armatura della cassaforma",
    attivita: "Posizionamento della cassaforma- Manovra della cassaforma dalla postazione comandi",
    descrizione: "L’operazione prevede il posizionamento della cassaforma nella zona in cui dovrà essere eseguito il getto. / La cassaforma viene manovrata da un operatore che comanda tutte le operazioni, da una postazione di comandi situata sulla stessa cassaforma. Nell’eseguire la manovra l’operatore è in piedi, con le mani sul quadro comandi e la schiena diritta",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Armatura e getto della calotta",
    fase: "Armatura della cassaforma",
    attivita: "Posizionamento della cassaforma Posizionamento della cassaforma – assistenza a terra",
    descrizione: "L’operazione prevede l’assistenza da terra durante il posizionamento della cassaforma. / Il carpentiere, da terra, fornisce, al carpentiere in postazione comandi, le indicazioni necessarie per manovrare correttamente la cassaforma. Nello svolgere questa attività, il carpentiere è in piedi ed in movimento per posizionarsi nelle postazioni più adatte a poter osservare i movimenti della cassaforma, ha generalmente un braccio disteso ed un braccio sollevato per mimare le indicazioni, la schiena è per quasi tutto il tempo curva",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 2, braccia: 2, gambe: 7, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Armatura e getto della calotta",
    fase: "Armatura della cassaforma",
    attivita: "Esecuzione della smorza",
    descrizione: "L’operazione prevede l’installazione ai lati della cassaforma di una struttura di contenimento del calcestruzzo che successivamente verrà gettato per la definizione della calotta. Il lavoratore durante l’attività alterna momenti in cui è in piedi a momenti in cui lavora in ginocchio con la schiena dritta e in alcune fasi curva e in torsione.",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }, { schiena: 1, braccia: 1, gambe: 6, carico: 1 }, { schiena: 4, braccia: 1, gambe: 2, carico: 1 }, { schiena: 4, braccia: 1, gambe: 6, carico: 1 }],
    classiModello: [1, 1, 2, 4],
  },
  {
    gruppo: "Armatura e getto della calotta",
    fase: "Getto della calotta",
    attivita: "Getto della calotta e vibratura del cemento",
    descrizione: "L’operazione prevede il getto del rivestimento definitivo. Il calcestruzzo viene pompato tramite una pompa posta sul piano di calpestio della galleria collegata alla tubazione di ingresso presente sulla cassaforma. Durante l’esecuzione del getto, il carpentiere è in cassaforma, in posizione in piedi, con le braccia distese e la schiena in diverse posizioni (diritta, curva, in torsione)",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Minatore / Minatore / Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Carpentiere/Ferraiolo / Addetto ripristini NC",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }, { schiena: 2, braccia: 1, gambe: 2, carico: 1 }, { schiena: 4, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1, 2, 2],
  },
  {
    gruppo: "Armatura e getto della calotta",
    fase: "Getto della calotta",
    attivita: "Assistenza al getto della calotta",
    descrizione: "L’assistenza al getto avviene normalmente da sotto la cassaforma, nei pressi della tramoggia dell’autobetoniera. / L’operatore che esegue l’assistenza al getto è in piedi, con le braccia distese e la schiena diritta.",
    rischio: "Posture incongrue",
    mansioni: "Carpentiere/Caposquadra / Carpentiere / Addetto ripristini NC / Caposquadra/Minatore / Minatore",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Armatura e getto della calotta",
    fase: "Disarmo e traslazione della cassaforma",
    attivita: "Disarmo della smorza",
    descrizione: "L’operazione prevede rimozione ai lati della cassaforma della struttura di contenimento del calcestruzzo che precedentemente è stato gettato per la definizione della calotta. Il lavoratore durante l’attività alterna momenti in cui è in piedi a momenti in cui lavora in ginocchio con la schiena dritta e in alcune fasi curva e in torsione.",
    rischio: "Posture Incongrue",
    mansioni: "Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ferraiolo",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }, { schiena: 1, braccia: 1, gambe: 6, carico: 1 }, { schiena: 4, braccia: 1, gambe: 2, carico: 1 }, { schiena: 4, braccia: 1, gambe: 6, carico: 1 }],
    classiModello: [1, 1, 2, 4],
  },
  {
    gruppo: "Armatura e getto della calotta",
    fase: "Disarmo e traslazione della cassaforma",
    attivita: "Spostamento delle scarpette",
    descrizione: "Una volta maturato il cls la cassaforma deve essere riposizionata per il getto successivo. Le scarpette sono dei robusti contrasti metallici che vengono posti sopra le murette e fungono da appoggio per la cassaforma e da contrasto durante il getto. Ad ogni spostamento le scarpette vengono sollevate e appoggiate su un ripiano posto alla base della cassaforma.  / Nell’eseguire l’attività il carpentiere è in posizione in piedi, con le braccia distese e la schiena curva",
    rischio: "Movimentazione manuale dei carichi / Posture incongrue",
    mansioni: "Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ferraiolo",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 3 }],
    classiModello: [3],
  },
  {
    gruppo: "Armatura e getto della calotta",
    fase: "Disarmo e traslazione della cassaforma",
    attivita: "Riposizionamento delle scarpette dopo la traslazione della cassaforma",
    descrizione: "Dopo il riposizionamento della cassaforma, le scarpette vengono rimesse nella posizione iniziale. / Nell’eseguire l’attività il carpentiere è in posizione in piedi, con le braccia distese e la schiena curva",
    rischio: "Movimentazione manuale dei carichi / Posture incongrue",
    mansioni: "Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ferraiolo",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 3 }],
    classiModello: [3],
  },
  {
    gruppo: "Arco rovescio",
    fase: "Scavo e smarino arco rovescio",
    attivita: "Scavo e smarino arco rovescio",
    descrizione: "L’operazione consiste nello scavo e contemporaneamente smarino dell’arco rovescio e viene eseguita dall’escavatorista che esegue anche il disgaggio del fronte e lo scavo delle murette. L’escavatorista è seduto sul sedile dell’escavatore, con le mani sui comandi del mezzo, la schiena diritta o leggermente curva",
    rischio: "Vibrazioni corpo intero / Posture incongrue",
    mansioni: "Escavatorista/ palista/Lancista / Escavatorista/Palista / Escavatorista/Palista/Mulettista / Escavatorista/Autista/Mulettista/Palista",
    posture: [{ schiena: 2, braccia: 1, gambe: 1, carico: 1 }, { schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [2, 1],
  },
  {
    gruppo: "Arco rovescio",
    fase: "Getto dell’arco rovescio",
    attivita: "Getto arco rovescio",
    descrizione: "",
    rischio: "Posture incongrue",
    mansioni: "Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Carpentiere/Ferraiolo / Addetto ripristini NC  / Caposquadra/Minatore / Minatore",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Arco rovescio",
    fase: "Getto dell’arco rovescio",
    attivita: "Vibratura del cemento",
    descrizione: "Durante il getto il cls viene vibrato tramite vibratori ad ago. Il carpentiere sostiene il vibratore con le mani ed esegue la vibratura stando in posizione in piedi, con le braccia che sorreggono il vibratore e la schiena curva",
    rischio: "Vibrazione sul mano-braccio / Posture incongrue",
    mansioni: "Caposquadra/Carpentiere/Mulettista / Carpentiere/Mulettista / Carpentiere/Caposquadra / Carpentiere / Carpentiere/Ripristini/Mulettista / Carpentiere/Ferraiolo / Addetto ripristini NC  / Caposquadra/Minatore / Minatore",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Manutenzione mezzi",
    attivita: "Utilizzo attrezzature in officina (trapano a colonna, mola, sega, ecc.)",
    descrizione: "L’operazione prevede l’utilizzo delle diverse attrezzature di cui è dotata l’officina meccanica. Il meccanico che utilizza le attrezzature è in posizione in piedi (davanti all’attrezzatura), con le braccia sul pezzo o sull’attrezzo e la schiena curva",
    rischio: "Posture incongrue",
    mansioni: "Capo Officina Meccanico / Fabbro Saldatore / Meccanico",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Manutenzione mezzi",
    attivita: "Interventi sui mezzi",
    descrizione: "L’operazione prevede l’intervento manuale sul mezzo da riparare. Le posture che il meccanico può assumere durante questi interventi possono essere di diverso tipo. Il meccanico può essere in piedi, con le braccia sulla macchina e la schiena curva oppure può essere in ginocchio con le braccia sopra il livello delle spalle e la schiena in torsione, oppure può essere sdraiato sotto il mezzo con le braccia sollevate. Nello svolgere l’attività spesso ha in mano un martello o altra attrezzatura o trasporto di cassette di attrezzi meccanici",
    rischio: "Posture incongrue / Movimentazione manuale dei carichi",
    mansioni: "Capo Officina Meccanico / Fabbro Saldatore / Meccanico",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }, { schiena: 3, braccia: 3, gambe: 6, carico: 1 }],
    classiModello: [2, 4],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Manutenzioni elettriche (su cavi, lampade, montaggio fari, sollevamento plafoniere ecc.)",
    attivita: "Utilizzo attrezzature in officina (trapano, cannello, ecc.)",
    descrizione: "L’operazione prevede l’utilizzo delle diverse attrezzature di cui è dotata l’officina. L’elettricista che utilizza le attrezzature è in posizione in piedi (davanti all’attrezzatura), con le braccia sul pezzo o sull’attrezzo e la schiena curva sul banco di lavoro",
    rischio: "Posture incongrue",
    mansioni: "Elettricista / Impiantista / Impiantista/Perforatore / Responsabile Impianti",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [2],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Manutenzioni elettriche (su cavi, lampade, montaggio fari, sollevamento plafoniere ecc.)",
    attivita: "Interventi di manutenzione",
    descrizione: "L’operazione prevede la manutenzione elettrica di cavi, lampade direttamente in galleria. / Le posture che l’elettricista può assumere durante questi interventi possono essere di diverso tipo. L’elettricista può essere in piedi, con le braccia sotto il livello delle spalle e la schiena curva oppure può essere in ginocchio con le braccia sopra il livello delle spalle e la schiena in torsione, oppure può essere in piedi con schiena dritta e con entrambe le braccia sopra il livello delle spalle per interventi diretti sul sistema di cavi posti a parapetto. Nello svolgere l’attività spesso ha in mano un utensile o altra attrezzatura, può inoltre trasportare una cassetta di attrezzi meccanici.",
    rischio: "Posture incongrue / Movimentazione manuale dei carichi",
    mansioni: "Elettricista / Impiantista / Impiantista/Perforatore / Responsabile Impianti",
    posture: [{ schiena: 2, braccia: 1, gambe: 2, carico: 1 }, { schiena: 3, braccia: 3, gambe: 6, carico: 1 }, { schiena: 1, braccia: 3, gambe: 2, carico: 1 }],
    classiModello: [2, 4, 1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Attività d’ufficio",
    attivita: "Attività al computer",
    descrizione: "Pesa dei materiali che in entrata e/o uscita dal cantiere necessitano di una verifica sul peso",
    rischio: "Posture Incongrue",
    mansioni: "Tecnico di cantiere-ASPP / Tecnico di cantiere / Direttore di cantiere",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Coordinamento mezzi in ingresso e uscita",
    attivita: "Coordinamento mezzi in ingresso e uscita",
    descrizione: "",
    rischio: "Posture incongrue",
    mansioni: "Addetto piazzale/Gruista",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Gestione dell’impianto di depurazione",
    attivita: "Gestione dell’impianto di depurazione",
    descrizione: "Verifica del corretto funzionamento dell’impianto di depurazione. L’addetto impianto di depurazione durante l’attività lavorativa è in piedi con la schiena diritta e le braccia sotto il livello delle spalle",
    rischio: "Posture incongrue",
    mansioni: "Addetto Impianto Depurazione Acqua",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Bagnatura Piste",
    attivita: "Bagnatura piste di cantiere",
    descrizione: "Bagnature delle piste di cantiere per. L’operatore alla guida del mezzo è seduto sul sedile, con le mani sul volante, la schiena diritta o leggermente curva.",
    rischio: "Vibrazioni sul corpo intero / Posture incongrue",
    mansioni: "Autista Servizi Generali / Assistente di cantiere / Addetto Piazzale/Gruista",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Pulizia Piste",
    attivita: "Pulizia tramite spazzatrice delle piste di cantiere",
    descrizione: "Bagnature delle piste di cantiere per. L’operatore alla guida del mezzo è seduto sul sedile, con le mani sul volante, la schiena diritta o leggermente curva.",
    rischio: "Vibrazioni sul corpo intero / Posture incongrue",
    mansioni: "Autista Servizi Generali / Assistente di cantiere / Addetto Piazzale/Gruista",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Attività di pesa",
    attivita: "Pesa dei materiali in entrata e/o uscita dal cantiere",
    descrizione: "",
    rischio: "Posture incongrue",
    mansioni: "Addetto Piazzale/Gruista / Assistente di cantiere",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Tutte le lavorazioni",
    attivita: "Sopralluoghi in galleria",
    descrizione: "Il capocantiere effettua periodici sopralluoghi all’interno delle varie aree del cantiere. Il sopralluogo avviene in piedi con le mani sotto il livello delle spalle e senza il sollevamento di alcun peso.",
    rischio: "Posture incongrue",
    mansioni: "Tecnico di cantiere-ASPP / Tecnico di cantiere / Direttore di cantiere",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Distribuzione Gasolio",
    attivita: "Operazioni di distribuzioni del gasolio",
    descrizione: "L’operatore alla guida è seduto sul sedile con le mani sul volante e la schiena dritta o leggermente curva, si occupa del rifornimento di gasolio dei mezzi di cantiere.",
    rischio: "Vibrazioni sul corpo intero / Posture incongrue",
    mansioni: "Addetto / Rifornimento Gasolio",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Conduzione Navetta",
    attivita: "Conduzione navetta",
    descrizione: "L’operatore è a supporto di tutti i lavoratori che devono spostarsi nel cantiere da un fronte all’altro o in esterno verso il campo base. L’operatore alla guida è seduto sul sedile con le mani sul volante e la schiena dritta o leggermente curva.",
    rischio: "Vibrazioni sul corpo intero / Posture incongrue",
    mansioni: "Autista Navetta",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Gestione Magazzino",
    attivita: "Gestione Magazzino",
    descrizione: "L’attività consiste nella gestione del magazzino, assiste allo scarico del materiale, si occupa di sistemare il materiale all’interno del magazzino negli scaffali, trasporta il materiale dall’interno del magazzino fino al camioncino per il rifornimento generale del cantiere.",
    rischio: "Posture Incongrue / -Movimentazione manuale dei carichi",
    mansioni: "Magazziniere/Responsabile Ufficio Attrezzature",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }],
    classiModello: [1],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Movimentazione materiali di cantiere",
    attivita: "Movimentazione materiali di cantiere",
    descrizione: "L’operazione consiste nella movimentazione di materiali di cantiere tramite sollevatore telescopico o autogrù. / L’operatore alla guida del sollevatore o dell’autogrù è seduto sul sedile del mezzo, con le mani sui comandi, la schiena diritta o leggermente curva in avanti per seguire l’operazione di movimentazione dei materiali",
    rischio: "Vibrazioni sul corpo intero / Posture incongrue",
    mansioni: "Autista/Minatore/Gruista / Addetto piazzale/Gruista",
    posture: [{ schiena: 1, braccia: 1, gambe: 1, carico: 1 }, { schiena: 2, braccia: 1, gambe: 2, carico: 1 }],
    classiModello: [1, 2],
  },
  {
    gruppo: "Attività a servizio del cantiere",
    fase: "Movimentazione materiali in magazzino",
    attivita: "Rifornimento generale del cantiere",
    descrizione: "",
    rischio: "Posture incongrue",
    mansioni: "Magazziniere/Responsabile Ufficio Attrezzature",
    posture: [{ schiena: 1, braccia: 1, gambe: 2, carico: 1 }, { schiena: 2, braccia: 1, gambe: 2, carico: 2 }, { schiena: 1, braccia: 3, gambe: 2, carico: 2 }],
    classiModello: [1, 2, 2],
  },
]
